# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'lottie-ios'
target 'Standard4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Standard4

end
